In [52]:
import pandas as pd
from datetime import date

In [57]:
df = pd.read_csv("/workspaces/Personal_Coding/Discogs Collection Modifier/zackdimondrecords1-collection-20260402-1501.csv")

In [58]:
backup = df

In [72]:
df_stock = df.dropna(subset =['Collection Notes'])
df_stock

,Catalog#,Artist,Title,Label,Format,Rating,Released,release_id,CollectionFolder,Date Added,Collection Price,Collection Sold Price,Collection Notes
0,"S 4208, 4208",Jerry Goldsmith,Patton (Original Motion Picture Score),"20th Century Fox Records, 20th Century Fox Rec...","LP, Album",NaN,1970,29799220,Record Collection #100,2025-07-28 11:17:56,NaN,NaN,A
3,4S-SP-106,Various,Made In Tennessee,4 Star Records,"LP, Comp",NaN,1977,4454379,Record Collection #97,2025-06-24 12:37:49,NaN,NaN,A
5,SP 5199,Amy Grant,Lead Me On,A&M Records,"LP, Album",NaN,1988,2096172,Record Collection #111,2026-01-23 14:42:02,7,NaN,A
7,SP-4249,Lee Michaels,Barrel,A&M Records,"LP, Album",NaN,1970,1226289,Record Collection #98,2026-04-01 22:36:08,NaN,NaN,A
8,SP-4575,Pablo Cruise,Lifeline,A&M Records,"LP, Album, Pit",NaN,1976,3874309,Record Collection #106,2025-10-24 14:29:06,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,WST-8490-LP,Dr. Charles S. Kendall,Morning Chimes,Word,"LP, Album",NaN,1970,5356478,Record Collection #97,2025-06-24 11:06:50,NaN,NaN,A
640,WST-8714,Evie (2),Gentle Moments,Word,LP,NaN,1976,3195892,Record Collection #111,2026-01-23 14:34:01,NaN,NaN,A
641,WST-8770,Evie (2),"Come On, Ring Those Bells",Word,"LP, Album, Lar",NaN,1977,17289814,Record Collection #111,2026-01-25 15:15:07,NaN,NaN,A
642,"WSB-8769, WSB 8769",Evie (2),A Little Song Of Joy For My Little Friends,"Word, Word","LP, Album",NaN,1978,1451769,Record Collection #111,2026-01-23 15:02:57,NaN,NaN,A
643,W 9163,The Dawnbusters (2),The Big Country,Wyncote,"LP, Album, Mono",NaN,1967,6980612,Record Collection #106,2025-10-24 15:15:16,NaN,NaN,A

In [60]:
df.columns

Index(['Catalog#', 'Artist', 'Title', 'Label', 'Format', 'Rating', 'Released',
       'release_id', 'CollectionFolder', 'Date Added', 'Collection Price',
       'Collection Sold Price', 'Collection Notes'],
      dtype='str')

In [61]:
df_sold = df[df['Collection Notes'].isna()]
df_sold.head()

,Catalog#,Artist,Title,Label,Format,Rating,Released,release_id,CollectionFolder,Date Added,Collection Price,Collection Sold Price,Collection Notes
1,T-414,Love Unlimited,Under The Influence Of Love Unlimited,20th Century Records,"LP, Album, P/Mixed, Ter",NaN,1973,580795,Record Collection #111,2026-01-25 18:22:01,NaN,NaN,NaN
2,T-433,Love Unlimited Orchestra,Rhapsody In White,20th Century Records,"LP, Album",NaN,1974,21270940,Individual Find,2026-03-23 07:07:24,NaN,NaN,NaN
4,SE 1024,Carpenters,Yesterday Once More,A&M Records,"2xLP, Comp, Mon",NaN,1984,3110567,Record Collection #106,2025-10-24 14:32:37,NaN,NaN,NaN
6,SP-3708,Supertramp,Breakfast In America,A&M Records,"LP, Album, Mon",NaN,1979,4450663,Record Collection #116,2026-03-11 11:51:35,NaN,NaN,NaN
10,SP-4896,Jeffrey Osborne,Jeffrey Osborne,A&M Records,"LP, Album, R,",NaN,1982,1545418,Record Collection #89,2025-05-07 07:34:34,NaN,NaN,NaN

In [62]:
df_sold['Blank'] = ''
df_sold =df_sold[['Blank','Artist', 'Title', 'CollectionFolder','Collection Price','Collection Sold Price','Date Added']]
df_sold.head()

,Blank,Artist,Title,CollectionFolder,Collection Price,Collection Sold Price,Date Added
1,,Love Unlimited,Under The Influence Of Love Unlimited,Record Collection #111,NaN,NaN,2026-01-25 18:22:01
2,,Love Unlimited Orchestra,Rhapsody In White,Individual Find,NaN,NaN,2026-03-23 07:07:24
4,,Carpenters,Yesterday Once More,Record Collection #106,NaN,NaN,2025-10-24 14:32:37
6,,Supertramp,Breakfast In America,Record Collection #116,NaN,NaN,2026-03-11 11:51:35
10,,Jeffrey Osborne,Jeffrey Osborne,Record Collection #89,NaN,NaN,2025-05-07 07:34:34

In [23]:
df_sold['CollectionFolder'].value_counts()

CollectionFolder
Record Collection #106    57
Record Collection #111    54
Record Collection #98     20
Record Collection #105    19
Individual Find           16
Record Collection #89     12
Record Collection #109    12
Record Collection #113    10
Record Collection #102     8
Record Collection #96      8
Record Collection #93      7
Record Collection #103     7
Uncategorized              6
Record Collection #104     5
Record Collection #100     5
Record Collection #114     5
Record Collection #97      5
Record Collection #108     4
Record Collection #112     4
Record Collection #101     3
Record Collection #91      3
Record Collection #107     2
Record Collection #116     1
Record Collection #92      1
Record Collection #115     1
Name: count, dtype: int64

In [35]:
df_sold['CollectionFolder']=df_sold['CollectionFolder'].replace('Uncategorized', 'Individual Find')

In [36]:
today = pd.Timestamp.today().normalize()

In [ ]:
df_sold['Date Added'] = pd.to_datetime(df_sold['Date Added'])
df_sold.loc[
    df_sold['CollectionFolder'] == 'Individual Find',
    'CollectionFolder'
] = (today - df_sold['Date Added']).dt.days.astype(str)

In [64]:
df_sold['Collection Price'] = df_sold['Collection Price'].fillna(3)
df_sold['Collection Sold Price'] = df_sold['Collection Sold Price'].fillna(df_sold['Collection Price'])
df_sold['Collection Sold Price'].value_counts()

Collection Sold Price
3       271
22.5      1
5         1
Name: count, dtype: int64

In [65]:
df_sold=df_sold[['Blank','Artist', 'Title', 'CollectionFolder','Collection Price','Collection Sold Price']]
df_sold.head()

,Blank,Artist,Title,CollectionFolder,Collection Price,Collection Sold Price
1,,Love Unlimited,Under The Influence Of Love Unlimited,Record Collection #111,3,3
2,,Love Unlimited Orchestra,Rhapsody In White,Individual Find,3,3
4,,Carpenters,Yesterday Once More,Record Collection #106,3,3
6,,Supertramp,Breakfast In America,Record Collection #116,3,3
10,,Jeffrey Osborne,Jeffrey Osborne,Record Collection #89,3,3

In [41]:
df_sold.to_csv("Sold.csv", index=False)

In [73]:
df_stock.columns

Index(['Catalog#', 'Artist', 'Title', 'Label', 'Format', 'Rating', 'Released',
       'release_id', 'CollectionFolder', 'Date Added', 'Collection Price',
       'Collection Sold Price', 'Collection Notes'],
      dtype='str')

In [83]:
df_stock= df_stock[['Artist', 'Title', 'Collection Price']]
df_stock['Collection Price']= df_stock['Collection Price'].fillna(3)

Collection Price
3     271
30      1
5       1
Name: count, dtype: int64