In [1]:
import pandas as pd

In [16]:
df = pd.read_csv("/workspaces/Personal_Coding/Discogs Collection Modifier/zackdimondrecords1-collection-20260402-0546.csv")

In [12]:
backup = df

In [18]:
df2 = df.dropna(subset =['Collection Notes'])
df2

,Catalog#,Artist,Title,Label,Format,Rating,Released,release_id,CollectionFolder,Date Added,Collection Media Condition,Collection Sleeve Condition,Collection Notes
0,"S 4208, 4208",Jerry Goldsmith,Patton (Original Motion Picture Score),"20th Century Fox Records, 20th Century Fox Rec...","LP, Album",NaN,1970,29799220,Record Collection #100,2025-07-28 11:17:56,NaN,NaN,A
3,4S-SP-106,Various,Made In Tennessee,4 Star Records,"LP, Comp",NaN,1977,4454379,Record Collection #97,2025-06-24 12:37:49,NaN,NaN,A
5,SP 5199,Amy Grant,Lead Me On,A&M Records,"LP, Album",NaN,1988,2096172,Record Collection #111,2026-01-23 14:42:02,NaN,NaN,A
8,SP-4575,Pablo Cruise,Lifeline,A&M Records,"LP, Album, Pit",NaN,1976,3874309,Record Collection #106,2025-10-24 14:29:06,NaN,NaN,A
9,SP-4836,Rita Coolidge,Greatest Hits,A&M Records,"LP, Comp, San",NaN,1980,1768031,Record Collection #111,2026-03-31 07:37:41,NaN,NaN,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
640,WST-8490-LP,Dr. Charles S. Kendall,Morning Chimes,Word,"LP, Album",NaN,1970,5356478,Record Collection #97,2025-06-24 11:06:50,NaN,NaN,A
641,WST-8714,Evie (2),Gentle Moments,Word,LP,NaN,1976,3195892,Record Collection #111,2026-01-23 14:34:01,NaN,NaN,A
642,WST-8770,Evie (2),"Come On, Ring Those Bells",Word,"LP, Album, Lar",NaN,1977,17289814,Record Collection #111,2026-01-25 15:15:07,NaN,NaN,A
643,"WSB-8769, WSB 8769",Evie (2),A Little Song Of Joy For My Little Friends,"Word, Word","LP, Album",NaN,1978,1451769,Record Collection #111,2026-01-23 15:02:57,NaN,NaN,A
644,W 9163,The Dawnbusters (2),The Big Country,Wyncote,"LP, Album, Mono",NaN,1967,6980612,Record Collection #106,2025-10-24 15:15:16,NaN,NaN,A

In [20]:
df_nulls = df[df['Collection Notes'].isna()]
df_nulls.head()

,Catalog#,Artist,Title,Label,Format,Rating,Released,release_id,CollectionFolder,Date Added,Collection Media Condition,Collection Sleeve Condition,Collection Notes
1,T-414,Love Unlimited,Under The Influence Of Love Unlimited,20th Century Records,"LP, Album, P/Mixed, Ter",NaN,1973,580795,Record Collection #111,2026-01-25 18:22:01,NaN,NaN,NaN
2,T-433,Love Unlimited Orchestra,Rhapsody In White,20th Century Records,"LP, Album",NaN,1974,21270940,Individual Find,2026-03-23 07:07:24,NaN,NaN,NaN
4,SE 1024,Carpenters,Yesterday Once More,A&M Records,"2xLP, Comp, Mon",NaN,1984,3110567,Record Collection #106,2025-10-24 14:32:37,NaN,NaN,NaN
6,SP-3708,Supertramp,Breakfast In America,A&M Records,"LP, Album, Mon",NaN,1979,4450663,Record Collection #116,2026-03-11 11:51:35,NaN,NaN,NaN
7,SP-4249,Lee Michaels,Barrel,A&M Records,"LP, Album",NaN,1970,1226289,Record Collection #98,2026-04-01 22:36:08,NaN,NaN,NaN

In [24]:
df_nulls['Blank'] = ''
df_nulls =df_nulls[['Blank','Artist', 'Title', 'CollectionFolder']]
df_nulls.info()

<class 'pandas.DataFrame'>
Index: 275 entries, 1 to 647
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Blank             275 non-null    str
 1   Artist            275 non-null    str
 2   Title             275 non-null    str
 3   CollectionFolder  275 non-null    str
dtypes: str(4)
memory usage: 10.7 KB